-- AUTO-GENERATED by tools/seed_from_dummyjson.py — do not hand-edit
-- Generated UTC: 2026-08-01 12:09:45
-- Source: DummyJSON (30 products)
-- Safe for DBs with existing Orders: soft-deactivates old catalog rows, inserts new ones.

USE LegacyEcommerceDb;
GO

-- Soft-hide previous catalog so layout tests show fresh DummyJSON products
UPDATE dbo.Product SET IsActive = 0 WHERE IsActive = 1;
GO

-- Ensure categories exist (by name)
IF NOT EXISTS (SELECT 1 FROM dbo.Category WHERE Name = N'Beauty')
    INSERT INTO dbo.Category (Name, ParentCategoryId, DisplayOrder)
    VALUES (N'Beauty', NULL, 100);
IF NOT EXISTS (SELECT 1 FROM dbo.Category WHERE Name = N'Fragrances')
    INSERT INTO dbo.Category (Name, ParentCategoryId, DisplayOrder)
    VALUES (N'Fragrances', NULL, 100);
IF NOT EXISTS (SELECT 1 FROM dbo.Category WHERE Name = N'Furniture')
    INSERT INTO dbo.Category (Name, ParentCategoryId, DisplayOrder)
    VALUES (N'Furniture', NULL, 100);
IF NOT EXISTS (SELECT 1 FROM dbo.Category WHERE Name = N'Groceries')
    INSERT INTO dbo.Category (Name, ParentCategoryId, DisplayOrder)
    VALUES (N'Groceries', NULL, 100);
GO

DECLARE @CatMap TABLE (Slug NVARCHAR(100) NOT NULL, CategoryId INT NOT NULL);
INSERT INTO @CatMap (Slug, CategoryId)
SELECT N'beauty', CategoryId FROM dbo.Category WHERE Name = N'Beauty';
INSERT INTO @CatMap (Slug, CategoryId)
SELECT N'fragrances', CategoryId FROM dbo.Category WHERE Name = N'Fragrances';
INSERT INTO @CatMap (Slug, CategoryId)
SELECT N'furniture', CategoryId FROM dbo.Category WHERE Name = N'Furniture';
INSERT INTO @CatMap (Slug, CategoryId)
SELECT N'groceries', CategoryId FROM dbo.Category WHERE Name = N'Groceries';

-- Product 1: Essence Mascara Lash Princess
DECLARE @Pid1 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Essence Mascara Lash Princess', N'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.', 9.99, N'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp', 99, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'beauty';
SET @Pid1 = SCOPE_IDENTITY();
IF @Pid1 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid1, N'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp', 0);
IF @Pid1 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid1, N'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp', 1);

-- Product 2: Eyeshadow Palette with Mirror
DECLARE @Pid2 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Eyeshadow Palette with Mirror', N'The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it''s convenient for on-the-go makeup application.', 19.99, N'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp', 34, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'beauty';
SET @Pid2 = SCOPE_IDENTITY();
IF @Pid2 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid2, N'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp', 0);
IF @Pid2 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid2, N'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp', 1);

-- Product 3: Powder Canister
DECLARE @Pid3 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Powder Canister', N'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.', 14.99, N'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp', 89, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'beauty';
SET @Pid3 = SCOPE_IDENTITY();
IF @Pid3 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid3, N'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp', 0);
IF @Pid3 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid3, N'https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp', 1);

-- Product 4: Red Lipstick
DECLARE @Pid4 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Red Lipstick', N'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.', 12.99, N'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp', 91, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'beauty';
SET @Pid4 = SCOPE_IDENTITY();
IF @Pid4 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid4, N'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp', 0);
IF @Pid4 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid4, N'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp', 1);

-- Product 5: Red Nail Polish
DECLARE @Pid5 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Red Nail Polish', N'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.', 8.99, N'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp', 79, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'beauty';
SET @Pid5 = SCOPE_IDENTITY();
IF @Pid5 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid5, N'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp', 0);
IF @Pid5 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid5, N'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp', 1);

-- Product 6: Calvin Klein CK One
DECLARE @Pid6 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Calvin Klein CK One', N'CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It''s a versatile fragrance suitable for everyday wear.', 49.99, N'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp', 29, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'fragrances';
SET @Pid6 = SCOPE_IDENTITY();
IF @Pid6 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid6, N'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp', 0);
IF @Pid6 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid6, N'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp', 1);
IF @Pid6 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid6, N'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp', 2);
IF @Pid6 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid6, N'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp', 3);

-- Product 7: Chanel Coco Noir Eau De
DECLARE @Pid7 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Chanel Coco Noir Eau De', N'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.', 129.99, N'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp', 58, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'fragrances';
SET @Pid7 = SCOPE_IDENTITY();
IF @Pid7 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid7, N'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp', 0);
IF @Pid7 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid7, N'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp', 1);
IF @Pid7 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid7, N'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp', 2);
IF @Pid7 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid7, N'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp', 3);

-- Product 8: Dior J'adore
DECLARE @Pid8 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Dior J''adore', N'J''adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.', 89.99, N'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/thumbnail.webp', 98, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'fragrances';
SET @Pid8 = SCOPE_IDENTITY();
IF @Pid8 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid8, N'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/thumbnail.webp', 0);
IF @Pid8 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid8, N'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/1.webp', 1);
IF @Pid8 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid8, N'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/2.webp', 2);
IF @Pid8 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid8, N'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/3.webp', 3);

-- Product 9: Dolce Shine Eau de
DECLARE @Pid9 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Dolce Shine Eau de', N'Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It''s a joyful and youthful scent.', 69.99, N'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp', 4, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'fragrances';
SET @Pid9 = SCOPE_IDENTITY();
IF @Pid9 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid9, N'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp', 0);
IF @Pid9 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid9, N'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp', 1);
IF @Pid9 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid9, N'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp', 2);
IF @Pid9 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid9, N'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp', 3);

-- Product 10: Gucci Bloom Eau de
DECLARE @Pid10 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Gucci Bloom Eau de', N'Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It''s a modern and romantic scent.', 79.99, N'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp', 91, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'fragrances';
SET @Pid10 = SCOPE_IDENTITY();
IF @Pid10 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid10, N'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp', 0);
IF @Pid10 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid10, N'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp', 1);
IF @Pid10 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid10, N'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp', 2);
IF @Pid10 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid10, N'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp', 3);

-- Product 11: Annibale Colombo Bed
DECLARE @Pid11 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Annibale Colombo Bed', N'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.', 1899.99, N'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp', 88, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'furniture';
SET @Pid11 = SCOPE_IDENTITY();
IF @Pid11 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid11, N'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp', 0);
IF @Pid11 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid11, N'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp', 1);
IF @Pid11 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid11, N'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp', 2);
IF @Pid11 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid11, N'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp', 3);

-- Product 12: Annibale Colombo Sofa
DECLARE @Pid12 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Annibale Colombo Sofa', N'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.', 2499.99, N'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp', 60, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'furniture';
SET @Pid12 = SCOPE_IDENTITY();
IF @Pid12 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid12, N'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp', 0);
IF @Pid12 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid12, N'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp', 1);
IF @Pid12 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid12, N'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/2.webp', 2);
IF @Pid12 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid12, N'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/3.webp', 3);

-- Product 13: Bedside Table African Cherry
DECLARE @Pid13 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Bedside Table African Cherry', N'The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.', 299.99, N'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp', 64, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'furniture';
SET @Pid13 = SCOPE_IDENTITY();
IF @Pid13 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid13, N'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp', 0);
IF @Pid13 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid13, N'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp', 1);
IF @Pid13 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid13, N'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/2.webp', 2);
IF @Pid13 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid13, N'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/3.webp', 3);

-- Product 14: Knoll Saarinen Executive Conference Chair
DECLARE @Pid14 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Knoll Saarinen Executive Conference Chair', N'The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.', 499.99, N'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp', 26, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'furniture';
SET @Pid14 = SCOPE_IDENTITY();
IF @Pid14 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid14, N'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp', 0);
IF @Pid14 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid14, N'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp', 1);
IF @Pid14 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid14, N'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/2.webp', 2);
IF @Pid14 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid14, N'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/3.webp', 3);

-- Product 15: Wooden Bathroom Sink With Mirror
DECLARE @Pid15 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Wooden Bathroom Sink With Mirror', N'The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.', 799.99, N'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp', 7, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'furniture';
SET @Pid15 = SCOPE_IDENTITY();
IF @Pid15 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid15, N'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp', 0);
IF @Pid15 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid15, N'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp', 1);
IF @Pid15 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid15, N'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/2.webp', 2);
IF @Pid15 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid15, N'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/3.webp', 3);

-- Product 16: Apple
DECLARE @Pid16 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Apple', N'Fresh and crisp apples, perfect for snacking or incorporating into various recipes.', 1.99, N'https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp', 8, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid16 = SCOPE_IDENTITY();
IF @Pid16 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid16, N'https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp', 0);
IF @Pid16 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid16, N'https://cdn.dummyjson.com/product-images/groceries/apple/1.webp', 1);

-- Product 17: Beef Steak
DECLARE @Pid17 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Beef Steak', N'High-quality beef steak, great for grilling or cooking to your preferred level of doneness.', 12.99, N'https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp', 86, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid17 = SCOPE_IDENTITY();
IF @Pid17 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid17, N'https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp', 0);
IF @Pid17 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid17, N'https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp', 1);

-- Product 18: Cat Food
DECLARE @Pid18 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Cat Food', N'Nutritious cat food formulated to meet the dietary needs of your feline friend.', 8.99, N'https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp', 46, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid18 = SCOPE_IDENTITY();
IF @Pid18 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid18, N'https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp', 0);
IF @Pid18 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid18, N'https://cdn.dummyjson.com/product-images/groceries/cat-food/1.webp', 1);

-- Product 19: Chicken Meat
DECLARE @Pid19 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Chicken Meat', N'Fresh and tender chicken meat, suitable for various culinary preparations.', 9.99, N'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp', 97, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid19 = SCOPE_IDENTITY();
IF @Pid19 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid19, N'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp', 0);
IF @Pid19 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid19, N'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp', 1);
IF @Pid19 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid19, N'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/2.webp', 2);

-- Product 20: Cooking Oil
DECLARE @Pid20 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Cooking Oil', N'Versatile cooking oil suitable for frying, sautéing, and various culinary applications.', 4.99, N'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp', 10, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid20 = SCOPE_IDENTITY();
IF @Pid20 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid20, N'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp', 0);
IF @Pid20 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid20, N'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp', 1);

-- Product 21: Cucumber
DECLARE @Pid21 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Cucumber', N'Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.', 1.49, N'https://cdn.dummyjson.com/product-images/groceries/cucumber/thumbnail.webp', 84, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid21 = SCOPE_IDENTITY();
IF @Pid21 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid21, N'https://cdn.dummyjson.com/product-images/groceries/cucumber/thumbnail.webp', 0);
IF @Pid21 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid21, N'https://cdn.dummyjson.com/product-images/groceries/cucumber/1.webp', 1);

-- Product 22: Dog Food
DECLARE @Pid22 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Dog Food', N'Specially formulated dog food designed to provide essential nutrients for your canine companion.', 10.99, N'https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp', 71, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid22 = SCOPE_IDENTITY();
IF @Pid22 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid22, N'https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp', 0);
IF @Pid22 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid22, N'https://cdn.dummyjson.com/product-images/groceries/dog-food/1.webp', 1);

-- Product 23: Eggs
DECLARE @Pid23 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Eggs', N'Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.', 2.99, N'https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp', 9, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid23 = SCOPE_IDENTITY();
IF @Pid23 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid23, N'https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp', 0);
IF @Pid23 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid23, N'https://cdn.dummyjson.com/product-images/groceries/eggs/1.webp', 1);

-- Product 24: Fish Steak
DECLARE @Pid24 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Fish Steak', N'Quality fish steak, suitable for grilling, baking, or pan-searing.', 14.99, N'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp', 74, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid24 = SCOPE_IDENTITY();
IF @Pid24 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid24, N'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp', 0);
IF @Pid24 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid24, N'https://cdn.dummyjson.com/product-images/groceries/fish-steak/1.webp', 1);

-- Product 25: Green Bell Pepper
DECLARE @Pid25 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Green Bell Pepper', N'Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.', 1.29, N'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp', 33, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid25 = SCOPE_IDENTITY();
IF @Pid25 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid25, N'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp', 0);
IF @Pid25 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid25, N'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/1.webp', 1);

-- Product 26: Green Chili Pepper
DECLARE @Pid26 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Green Chili Pepper', N'Spicy green chili pepper, ideal for adding heat to your favorite recipes.', 0.99, N'https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp', 3, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid26 = SCOPE_IDENTITY();
IF @Pid26 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid26, N'https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp', 0);
IF @Pid26 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid26, N'https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/1.webp', 1);

-- Product 27: Honey Jar
DECLARE @Pid27 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Honey Jar', N'Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.', 6.99, N'https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp', 34, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid27 = SCOPE_IDENTITY();
IF @Pid27 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid27, N'https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp', 0);
IF @Pid27 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid27, N'https://cdn.dummyjson.com/product-images/groceries/honey-jar/1.webp', 1);

-- Product 28: Ice Cream
DECLARE @Pid28 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Ice Cream', N'Creamy and delicious ice cream, available in various flavors for a delightful treat.', 5.49, N'https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp', 27, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid28 = SCOPE_IDENTITY();
IF @Pid28 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid28, N'https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp', 0);
IF @Pid28 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid28, N'https://cdn.dummyjson.com/product-images/groceries/ice-cream/1.webp', 1);
IF @Pid28 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid28, N'https://cdn.dummyjson.com/product-images/groceries/ice-cream/2.webp', 2);
IF @Pid28 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid28, N'https://cdn.dummyjson.com/product-images/groceries/ice-cream/3.webp', 3);
IF @Pid28 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid28, N'https://cdn.dummyjson.com/product-images/groceries/ice-cream/4.webp', 4);

-- Product 29: Juice
DECLARE @Pid29 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Juice', N'Refreshing fruit juice, packed with vitamins and great for staying hydrated.', 3.99, N'https://cdn.dummyjson.com/product-images/groceries/juice/thumbnail.webp', 50, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid29 = SCOPE_IDENTITY();
IF @Pid29 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid29, N'https://cdn.dummyjson.com/product-images/groceries/juice/thumbnail.webp', 0);
IF @Pid29 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid29, N'https://cdn.dummyjson.com/product-images/groceries/juice/1.webp', 1);

-- Product 30: Kiwi
DECLARE @Pid30 INT;
INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)
SELECT c.CategoryId, N'Kiwi', N'Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.', 2.49, N'https://cdn.dummyjson.com/product-images/groceries/kiwi/thumbnail.webp', 0, 1, GETDATE()
FROM @CatMap c WHERE c.Slug = N'groceries';
SET @Pid30 = SCOPE_IDENTITY();
IF @Pid30 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid30, N'https://cdn.dummyjson.com/product-images/groceries/kiwi/thumbnail.webp', 0);
IF @Pid30 IS NOT NULL
    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)
    VALUES (@Pid30, N'https://cdn.dummyjson.com/product-images/groceries/kiwi/1.webp', 1);

PRINT N'DummyJSON catalog seed complete.';
SELECT c.Name AS Category, COUNT(*) AS ActiveProducts
FROM dbo.Product p
INNER JOIN dbo.Category c ON c.CategoryId = p.CategoryId
WHERE p.IsActive = 1
GROUP BY c.Name
ORDER BY c.Name;
GO
