"""
Fetch products from DummyJSON (free, no API key) and write a SQL seed file
for LegacyEcommerceDb, then optionally print how to apply it.

Usage:
  python tools/seed_from_dummyjson.py
  python tools/seed_from_dummyjson.py --limit 30 --apply
"""

from __future__ import annotations

import argparse
import json
import ssl
import urllib.request
from collections import OrderedDict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_SQL = ROOT / "database" / "05_SeedCatalogFromDummyJson.sql"
API = "https://dummyjson.com/products?limit={limit}&skip=0"
URL_MAX = 300


def fetch_products(limit: int) -> list[dict]:
    ctx = ssl.create_default_context()
    url = API.format(limit=limit)
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": "LegacyEcommerceSeed/1.0 (+local-dev)",
            "Accept": "application/json",
        },
    )
    with urllib.request.urlopen(req, context=ctx, timeout=60) as resp:
        payload = json.loads(resp.read().decode("utf-8"))
    return list(payload.get("products") or [])


def sql_str(value: str | None) -> str:
    if value is None:
        return "NULL"
    cleaned = (
        value.replace("\r", " ")
        .replace("\n", " ")
        .replace("'", "''")
        .strip()
    )
    return "N'" + cleaned + "'"


def clip_url(url: str | None) -> str | None:
    if not url:
        return None
    url = url.strip()
    if len(url) > URL_MAX:
        return url[:URL_MAX]
    return url


def title_case_category(slug: str) -> str:
    return " ".join(part.capitalize() for part in slug.replace("_", "-").split("-"))


def build_sql(products: list[dict]) -> str:
    # Preserve insertion order of categories
    categories: "OrderedDict[str, str]" = OrderedDict()
    for p in products:
        slug = (p.get("category") or "general").strip().lower()
        if slug not in categories:
            categories[slug] = title_case_category(slug)

    lines: list[str] = []
    lines.append("-- AUTO-GENERATED by tools/seed_from_dummyjson.py — do not hand-edit")
    lines.append(f"-- Generated UTC: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"-- Source: DummyJSON ({len(products)} products)")
    lines.append("-- Safe for DBs with existing Orders: soft-deactivates old catalog rows, inserts new ones.")
    lines.append("")
    lines.append("USE LegacyEcommerceDb;")
    lines.append("GO")
    lines.append("")
    lines.append("-- Soft-hide previous catalog so layout tests show fresh DummyJSON products")
    lines.append("UPDATE dbo.Product SET IsActive = 0 WHERE IsActive = 1;")
    lines.append("GO")
    lines.append("")
    lines.append("-- Ensure categories exist (by name)")
    for name in categories.values():
        lines.append(
            "IF NOT EXISTS (SELECT 1 FROM dbo.Category WHERE Name = {0})\n"
            "    INSERT INTO dbo.Category (Name, ParentCategoryId, DisplayOrder)\n"
            "    VALUES ({0}, NULL, 100);".format(sql_str(name))
        )
    lines.append("GO")
    lines.append("")
    lines.append("DECLARE @CatMap TABLE (Slug NVARCHAR(100) NOT NULL, CategoryId INT NOT NULL);")
    for slug, name in categories.items():
        lines.append(
            "INSERT INTO @CatMap (Slug, CategoryId)\n"
            "SELECT {0}, CategoryId FROM dbo.Category WHERE Name = {1};".format(
                sql_str(slug), sql_str(name)
            )
        )
    lines.append("")

    for idx, p in enumerate(products, start=1):
        slug = (p.get("category") or "general").strip().lower()
        name = (p.get("title") or f"Product {idx}")[:200]
        desc = p.get("description") or ""
        price = float(p.get("price") or 0)
        stock = int(p.get("stock") or 0)
        # Keep at least one OOS sample for layout/tests
        if idx == len(products):
            stock = 0
        thumb = clip_url(p.get("thumbnail") or (p.get("images") or [None])[0])
        images = []
        for u in p.get("images") or []:
            cu = clip_url(u)
            if cu and cu not in images:
                images.append(cu)
        if thumb and thumb not in images:
            images.insert(0, thumb)
        images = images[:6]

        lines.append(f"-- Product {idx}: {name.replace('--', '-')}")
        lines.append("DECLARE @Pid{0} INT;".format(idx))
        lines.append(
            "INSERT INTO dbo.Product (CategoryId, Name, Description, Price, ThumbnailUrl, Stock, IsActive, CreatedDate)\n"
            "SELECT c.CategoryId, {name}, {desc}, {price}, {thumb}, {stock}, 1, GETDATE()\n"
            "FROM @CatMap c WHERE c.Slug = {slug};\n"
            "SET @Pid{idx} = SCOPE_IDENTITY();".format(
                idx=idx,
                name=sql_str(name),
                desc=sql_str(desc),
                price=f"{price:.2f}",
                thumb=sql_str(thumb) if thumb else "NULL",
                stock=stock,
                slug=sql_str(slug),
            )
        )
        for order, img in enumerate(images):
            lines.append(
                "IF @Pid{idx} IS NOT NULL\n"
                "    INSERT INTO dbo.ProductImage (ProductId, Url, DisplayOrder)\n"
                "    VALUES (@Pid{idx}, {url}, {order});".format(
                    idx=idx, url=sql_str(img), order=order
                )
            )
        lines.append("")

    lines.append("PRINT N'DummyJSON catalog seed complete.';")
    lines.append(
        "SELECT c.Name AS Category, COUNT(*) AS ActiveProducts\n"
        "FROM dbo.Product p\n"
        "INNER JOIN dbo.Category c ON c.CategoryId = p.CategoryId\n"
        "WHERE p.IsActive = 1\n"
        "GROUP BY c.Name\n"
        "ORDER BY c.Name;"
    )
    lines.append("GO")
    lines.append("")
    return "\n".join(lines)


def apply_sql(sql_path: Path) -> None:
    import subprocess

    sqlcmd = r"C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\SQLCMD.EXE"
    cmd = [sqlcmd, "-S", r".\SQLEXPRESS", "-E", "-i", str(sql_path)]
    print("Running:", " ".join(cmd))
    subprocess.check_call(cmd)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=30, help="How many DummyJSON products to import")
    parser.add_argument("--apply", action="store_true", help="Run SQLCMD against .\\SQLEXPRESS after writing SQL")
    args = parser.parse_args()

    print(f"Fetching {args.limit} products from DummyJSON...")
    products = fetch_products(args.limit)
    if not products:
        raise SystemExit("No products returned from DummyJSON.")

    sql = build_sql(products)
    OUT_SQL.parent.mkdir(parents=True, exist_ok=True)
    OUT_SQL.write_text(sql, encoding="utf-8")
    print(f"Wrote {OUT_SQL} ({len(products)} products)")

    if args.apply:
        apply_sql(OUT_SQL)
        print("Applied to LegacyEcommerceDb.")
    else:
        print("Apply with:")
        print(
            r'  SQLCMD -S .\SQLEXPRESS -E -i database\05_SeedCatalogFromDummyJson.sql'
        )


if __name__ == "__main__":
    main()
